import bpy
import importlib

from ...utils import copy_bone
from ...utils import make_deformer_name, strip_org
from ...utils import create_bone_widget, create_widget, create_cube_widget
from ...utils import connected_children_names, has_connected_children

from . import pantin_utils

importlib.reload(pantin_utils)

class Rig:
    def __init__(self, obj, bone_name, params):
        self.obj = obj
        self.org_bones = [bone_name] + connected_children_names(obj, bone_name)[:3]
        self.params = params


    def generate(self):
        bpy.ops.object.mode_set(mode='EDIT')
        
        ctrl_chain = []
        def_chain = []

        eb = self.obj.data.edit_bones
        for i, b in enumerate(self.org_bones):
            # Control bones
            ctrl_bone = copy_bone(self.obj, b)
            ctrl_bone_e = eb[ctrl_bone]

            # Name
            ctrl_bone_e.name = strip_org(b)

            # Parenting
            if i == 0:
                # First bone
                ctrl_bone_e.parent = eb[self.org_bones[0]].parent
            else:
                # The rest
                ctrl_bone_e.parent = eb[ctrl_chain[-1]]

            # Add to list
            ctrl_chain += [ctrl_bone_e.name]

            # Def bones
            def_bone = pantin_utils.create_deformation(self.obj, b, self.params.Z_index, i)
            def_chain.append(def_bone)

        bpy.ops.object.mode_set(mode='OBJECT')
        pb = self.obj.pose.bones

        # Widgets
        pelvis = ctrl_chain[0]
        abdomen = ctrl_chain[1]
        torso = ctrl_chain[2]
        shoulder = ctrl_chain[3]

        create_cube_widget(self.obj, pelvis, radius=1.0)

        for bone in ctrl_chain[1:]:
            pantin_utils.create_capsule_widget(self.obj, bone, head_tail=0.5)
            # create_widget(self.obj, bone)

        # Constraints
        for org, ctrl in zip(self.org_bones, ctrl_chain):
            con = pb[org].constraints.new('COPY_TRANSFORMS')
            con.name = "copy_transforms"
            con.target = self.obj
            con.subtarget = ctrl
            
def add_parameters(params):
    params.Z_index = bpy.props.IntProperty(name="Indice Z", default=0, description="Définit l'ordre des membres dans l'espace")
    params.mutable_order = bpy.props.BoolProperty(name="Ordre change", default=True, description="Ce membre peut changer de profondeur")

def parameters_ui(layout, params):
    """ Create the ui for the rig parameters.
    """
    r = layout.row()
    r.prop(params, "Z_index")
    r = layout.row()
    r.prop(params, "mutable_order")

def create_sample(obj):
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    bones = {}

    bone = arm.edit_bones.new('Bassin')
    bone.head[:] = 0.0025, 0.0000, 0.7926
    bone.tail[:] = 0.0038, 0.0000, 0.9127
    bone.roll = -3.1311
    bone.use_connect = False
    bones['Bassin'] = bone.name
    bone = arm.edit_bones.new('Abdomen')
    bone.head[:] = 0.0038, 0.0000, 0.9127
    bone.tail[:] = 0.0197, 0.0000, 1.0736
    bone.roll = -3.0427
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bassin']]
    bones['Abdomen'] = bone.name
    bone = arm.edit_bones.new('Torse')
    bone.head[:] = 0.0197, 0.0000, 1.0736
    bone.tail[:] = 0.0654, 0.0000, 1.2325
    bone.roll = -2.8616
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Abdomen']]
    bones['Torse'] = bone.name
    bone = arm.edit_bones.new('Epaule')
    bone.head[:] = 0.0654, 0.0000, 1.2325
    bone.tail[:] = 0.1611, 0.0000, 1.3800
    bone.roll = -2.5661
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Torse']]
    bones['Epaule'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['Bassin']]
    pbone.rigify_type = 'pantin.torso'
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    try:
        pbone.rigify_parameters.Z_index = 2
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Abdomen']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    pbone = obj.pose.bones[bones['Torse']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone = obj.pose.bones[bones['Epaule']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone
