import bpy


def create(obj):
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(28):
        arm.rigify_layers.add()

    arm.rigify_layers[0].name = "Tete"
    arm.rigify_layers[0].row = 1
    arm.rigify_layers[1].name = " "
    arm.rigify_layers[1].row = 1
    arm.rigify_layers[2].name = "Torse"
    arm.rigify_layers[2].row = 2
    arm.rigify_layers[3].name = " "
    arm.rigify_layers[3].row = 1
    arm.rigify_layers[4].name = "Bras Gauche"
    arm.rigify_layers[4].row = 3
    arm.rigify_layers[5].name = ""
    arm.rigify_layers[5].row = 1
    arm.rigify_layers[6].name = "Jambe Gauche"
    arm.rigify_layers[6].row = 4
    arm.rigify_layers[7].name = " "
    arm.rigify_layers[7].row = 1
    arm.rigify_layers[8].name = "Torse"
    arm.rigify_layers[8].row = 5
    arm.rigify_layers[9].name = " "
    arm.rigify_layers[9].row = 1
    arm.rigify_layers[10].name = " "
    arm.rigify_layers[10].row = 1
    arm.rigify_layers[11].name = " "
    arm.rigify_layers[11].row = 1
    arm.rigify_layers[12].name = " "
    arm.rigify_layers[12].row = 1
    arm.rigify_layers[13].name = " "
    arm.rigify_layers[13].row = 1
    arm.rigify_layers[14].name = " "
    arm.rigify_layers[14].row = 1
    arm.rigify_layers[15].name = " "
    arm.rigify_layers[15].row = 1
    arm.rigify_layers[16].name = " "
    arm.rigify_layers[16].row = 1
    arm.rigify_layers[17].name = " "
    arm.rigify_layers[17].row = 1
    arm.rigify_layers[18].name = " "
    arm.rigify_layers[18].row = 1
    arm.rigify_layers[19].name = " "
    arm.rigify_layers[19].row = 1
    arm.rigify_layers[20].name = "Bras Droit"
    arm.rigify_layers[20].row = 3
    arm.rigify_layers[21].name = " "
    arm.rigify_layers[21].row = 1
    arm.rigify_layers[22].name = "Jambe Droite"
    arm.rigify_layers[22].row = 4
    arm.rigify_layers[23].name = " "
    arm.rigify_layers[23].row = 1
    arm.rigify_layers[24].name = " "
    arm.rigify_layers[24].row = 1
    arm.rigify_layers[25].name = " "
    arm.rigify_layers[25].row = 1
    arm.rigify_layers[26].name = " "
    arm.rigify_layers[26].row = 1
    arm.rigify_layers[27].name = " "
    arm.rigify_layers[27].row = 1

    bones = {}

    bone = arm.edit_bones.new('Bassin')
    bone.head[:] = 0.0515, -0.0000, 0.8916
    bone.tail[:] = 0.0878, -0.0000, 1.0483
    bone.roll = -2.9142
    bone.use_connect = False
    bones['Bassin'] = bone.name
    bone = arm.edit_bones.new('Jambe haut')
    bone.head[:] = 0.0515, -0.0000, 0.8916
    bone.tail[:] = 0.0261, -0.0000, 0.4917
    bone.roll = 0.0634
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Bassin']]
    bones['Jambe haut'] = bone.name
    bone = arm.edit_bones.new('Abdomen')
    bone.head[:] = 0.0878, -0.0000, 1.0483
    bone.tail[:] = 0.0729, -0.0000, 1.1827
    bone.roll = -3.2517
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bassin']]
    bones['Abdomen'] = bone.name
    bone = arm.edit_bones.new('Jambe bas')
    bone.head[:] = 0.0261, -0.0000, 0.4917
    bone.tail[:] = -0.0053, 0.0000, 0.0769
    bone.roll = 0.0757
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Jambe haut']]
    bones['Jambe bas'] = bone.name
    bone = arm.edit_bones.new('Thorax')
    bone.head[:] = 0.0729, -0.0000, 1.1827
    bone.tail[:] = 0.0644, -0.0000, 1.3085
    bone.roll = -3.2094
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Abdomen']]
    bones['Thorax'] = bone.name
    bone = arm.edit_bones.new('Pied')
    bone.head[:] = -0.0053, 0.0000, 0.0769
    bone.tail[:] = 0.0532, -0.0000, 0.0250
    bone.roll = -0.8451
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Jambe bas']]
    bones['Pied'] = bone.name
    bone = arm.edit_bones.new('Talon')
    bone.head[:] = -0.0053, 0.0000, 0.0769
    bone.tail[:] = -0.0410, -0.0000, 0.0027
    bone.roll = -2.6932
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Jambe bas']]
    bones['Talon'] = bone.name
    bone = arm.edit_bones.new('Buste')
    bone.head[:] = 0.0644, -0.0000, 1.3085
    bone.tail[:] = 0.0549, -0.0000, 1.4061
    bone.roll = -3.2388
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thorax']]
    bones['Buste'] = bone.name
    bone = arm.edit_bones.new('Orteil')
    bone.head[:] = 0.0532, -0.0000, 0.0250
    bone.tail[:] = 0.1154, -0.0000, 0.0230
    bone.roll = -1.5391
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Pied']]
    bones['Orteil'] = bone.name
    bone = arm.edit_bones.new('Cou')
    bone.head[:] = 0.0549, -0.0000, 1.4061
    bone.tail[:] = 0.0815, -0.0000, 1.4743
    bone.roll = -2.7688
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Buste']]
    bones['Cou'] = bone.name
    bone = arm.edit_bones.new('Bras haut')
    bone.head[:] = 0.0056, -0.0000, 1.3408
    bone.tail[:] = 0.0100, -0.0000, 1.1262
    bone.roll = -0.0201
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Buste']]
    bones['Bras haut'] = bone.name
    bone = arm.edit_bones.new('Pointe')
    bone.head[:] = 0.1071, -0.0000, 0.0021
    bone.tail[:] = 0.1892, -0.0000, 0.0021
    bone.roll = -1.5708
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Orteil']]
    bones['Pointe'] = bone.name
    bone = arm.edit_bones.new('Tete')
    bone.head[:] = 0.0815, -0.0000, 1.4743
    bone.tail[:] = 0.1136, -0.0000, 1.6196
    bone.roll = -2.9241
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cou']]
    bones['Tete'] = bone.name
    bone = arm.edit_bones.new('Bras bas')
    bone.head[:] = 0.0100, -0.0000, 1.1262
    bone.tail[:] = 0.0383, -0.0000, 0.8731
    bone.roll = -0.1117
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bras haut']]
    bones['Bras bas'] = bone.name
    bone = arm.edit_bones.new('Cou_pied.ik')
    bone.head[:] = -0.0952, -0.0000, 0.0890
    bone.tail[:] = -0.1901, -0.0000, 0.0890
    bone.roll = 1.5708
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Pointe']]
    bones['Cou_pied.ik'] = bone.name
    bone = arm.edit_bones.new('Machoire')
    bone.head[:] = 0.0767, -0.0000, 1.4961
    bone.tail[:] = 0.1508, -0.0000, 1.4473
    bone.roll = -0.9887
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Tete']]
    bones['Machoire'] = bone.name
    bone = arm.edit_bones.new('Main')
    bone.head[:] = 0.0383, -0.0000, 0.8731
    bone.tail[:] = 0.0383, -0.0000, 0.7657
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Bras bas']]
    bones['Main'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['Bassin']]
    pbone.rigify_type = 'pantin.torso'
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.Z_index = 3
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.mutable_order = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.members_number = 5
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Jambe haut']]
    pbone.rigify_type = 'pantin.leg'
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.Z_index = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.joint_name = "Genou"
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.right_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Abdomen']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Jambe bas']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Thorax']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Pied']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Talon']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Buste']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Orteil']]
    pbone.rigify_type = ''
    pbone.lock_location = (True, True, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Cou']]
    pbone.rigify_type = 'pantin.head'
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.Z_index = 2
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.mutable_order = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Bras haut']]
    pbone.rigify_type = 'pantin.arm'
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.right_layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False]
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.joint_name = "Coude"
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Pointe']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Tete']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Bras bas']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Cou_pied.ik']]
    pbone.rigify_type = ''
    pbone.lock_location = (True, True, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Machoire']]
    pbone.rigify_type = ''
    pbone.lock_location = (True, True, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Main']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, True)
    pbone.lock_rotation = (True, True, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XZY'
    pbone.bone.layers = [False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        arm.edit_bones.active = bone

    arm.layers = [(x in [0, 2, 4, 6]) for x in range(32)]

if __name__ == "__main__":
    create(bpy.context.active_object)